name: Build and publish
on:
  push:
    branches: [main]
jobs:
  Upload-ECF-Submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Create PR for file artifacts
      run: |
        TARGET_REPO="https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/armhil/armhil.github.io.git"
        # Clone the target repository into a folder named "target-repo"
        git config --global user.email "arman.hilmioglu@gmail.com"
        git config --global user.name "armhil"
        git clone "$TARGET_REPO" target-repo
        cd target-repo
        # Create a new branch with a timestamp-based name
        BRANCH="add-ecf-submission-artifacts-$(date +%s)"
        git checkout -b "$BRANCH"
        # Copy build artifacts from current workspace into the target repo folder
        cp -R ../docs/* ./easy-code-formatter/documents/
        cp -R ../docs/images/* ./easy-code-formatter/images/
        cp -R ../docs/icons/* ./easy-code-formatter/icons/
        git add .
        # Check if there are staged changes
        if git diff --staged --quiet; then
          echo "No changes to commit. Exiting."
          exit 0
        else
          git commit -m "Add file artifacts from ecf submission"
          git push origin "$BRANCH"
          # Authenticate GitHub CLI using the secret token
          echo "${{ secrets.TARGET_REPO_TOKEN }}" | gh auth login --with-token
          # Create a pull request targeting the main branch
          gh pr create --title "Add file artifacts from ecf submission" --body "This PR includes the latest file artifacts from ecf submission." --base main
        fi